// app/layout.tsx
import Sidebar from '@/components/sidebar';
import { ReactNode } from 'react';
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>My Dashboard App</title>
      </head>
      <body className="flex">
        <Sidebar />
        <main className="flex-1 p-6 relative">
          {children}
        </main>
      </body>
    </html>
  );
}

